### ISSUE TITLE
TTNN Generic Runtime Interface

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#111]
This is a high level umbrella issue intended to give an overview of what we want to start building for a ttnn generic op.

First we should sync with Artem and Eyon and get their thoughts and opinion.  Any new APIs we create here will need sign off from them.

In the meantime, I think the below steps would be worth prototyping so we know what APIs to request and have a concrete plan for how this can work and interact with compiler needs.

Steps:
- Build / clone tt-metal, run a simple TTNN Eltwise op (https://github.com/tenstorrent/tt-metal/blob/main/tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.hpp)
- Familiarize yourself with the construction of the op:
  - How CBs are constructed
  - How kernels are built
  - How Programs are constructed
- Create a new ttnn generic op interface something like:
```
void run_generic(std::vector<Tensor> const& tensors, ProgramDesc programDesc);
```
  - Extract the above eltwise kernels and embed them at the test level
  - Pass the tensors, kernels, and CB descs into the ttnn generic function

**Comment by mbezuljTT** [comment]
Sharing update per our conversation I have a generic op that is tested on couple examples like unary sqrt interleaved, unary sharded rely, binary add interleaved and binary add sharded. 

Caching, python bindings and ethernet kernels are not implemented. 

@pjanevskiTT will take a look into testing softmax and matmul to discover if we are fundamentally missing something. And will look to implement caching. 

python bindings and ethernet kernels should be straighforward to add if/when we need them.

Sharing **GenericOpDeviceOperation::operation_attributes_t** that is equivalent to ProgramDesc from Nick's original message - this is work in progress version and we are yet to get feedback from TTNN folks. 

```
struct circular_buffer_attributes_t {
    CoreRangeSet core_spec;
    uint32_t total_size;
    uint32_t page_size;
    tt::DataFormat data_format;

    // this needs better solution as we now have input tensors (std::vector) and output tensor so index is not great
    std::optional<int> set_globally_allocated_address = std::nullopt; // an index to io_tensors that will set globally allocated address on CB
};

struct data_movement_attributes_t {
    CoreRangeSet core_spec;
    std::string kernel_path;
    tt::tt_metal::DataMovementConfig config;
    std::unordered_map<CoreCoord, std::vector<uint32_t>> runtime_args_per_core = {};
};

struct compute_attributes_t {
    CoreRangeSet core_spec;
    std::string  kernel_path;
    tt::tt_metal::ComputeConfig config;
    std::unordered_map<CoreCoord, std::vector<uint32_t>> runtime_args_per_core = {};
};

struct operation_attributes_t {
    std::unordered_map<uint8_t, circular_buffer_attributes_t> circular_buffer_attributes;
    std::vector<data_movement_attributes_t> data_movement_attributes;
    // Ethernet not supported at the moment.
    // std::optional<tt::metal::EthernetConfig> ethernetConfig;
    std::vector<compute_attributes_t> compute_attributes;
};
```

**Comment by pjanevskiTT** [comment]
Just to write down progress from the last update and expand on the work we have done so far for TTNN generic op

### TTNN generic op structure

We wanted to confirm that the generic op structure has everything it needs to run custom setup of kernels, circular buffers,... In order to have confidence about that, we have additionaly tested

- Softmax op - point of the test is to confirm whether we can support intermed circular buffers. Since these buffers are setup in a same way as input and output circular buffers, this wasn't a problem and the test passed
- Matmul - point of the test is to confirm that we can support different kernels being loaded to different cores. Matmul is the obvious example of this, so it was the best test to try this on. Everything passed so we haven't changed structure of the TTNN generic op since the last update. 

There are however improvements that can be made to generic op structure in terms of avoiding copying of objects, but since there was additional work to do in order to run PoC all the way through tt-mlir/tt-forge, we have continued working in that area, and deprioritized that and caching of the op as well

### TT-MLIR work

Good starting point to understand the work done on generic op through tt-mlir (from top to bottom) is [this comment](https://github.com/tenstorrent/tt-mlir/issues/201#issuecomment-2293746398)

Related to this issue, we are going to track work done from TTNN dialect to the bottom (TTNN/metal). So far we have done

- Serialization of the generic op from TTNN dialect to flatbuffer using `--ttnn-to-flatbuffer` pipeline. We have serialized general op info and input and output tensors

- TTRT support for reading flatbuffer containing serialized information about generic op

- TTRT support for preparing and packing data from flatbuffer to GenericOpDeviceOperation::operation_attributes_t, described in the previous comment on this issue

### Topics to discuss

I think the implementation above helped us better understand what the general flow of running generic op is going to be, so I would like to add few topics we can discuss either in the issue or in the meeting

- Can we support customer providing custom programs in order to calculate compile/runtime arguments? To me, it looks like the best place to do this is all the way up in tt-forge. Kristijan is working on creating the interface, through which customer could call generic op. I think we should just provide interface where you can pass numbers which are calculated somewhere before calling generic op

- [program.cpp](https://github.com/tenstorrent/tt-mlir/blob/main/runtime/lib/ttnn/program.cpp) is growing by every op. Generic op is going to have a lot of code required to even prepare actual call to TTNN, so maybe we need to have a way of doing this, either on op to op basis, or for all ops. Basically keep in `program.cpp` only actual calls to TTNN interface

- We are building tt-mlir on ubuntu 22 and the latest supported image for tt-metal standalone build is ubuntu 20.4. This makes things a bit difficult if you want to fix something in Metal when you are in tt-mlir and maybe test it on it's own. Maybe there is the argument that we don't even want to do this, but it looks like trying to enable metal to build on ubuntu 22 could make our life easier when working in ttrt 

### TODOs

TODOs left in order to support running TTNN generic op from TTIR dialect

- [ ] Serialize other attributes of generic op to flatbuffer (compute kernel attributes, circular buffer, data movement)
- [ ] Add runtime arguments to generic op both in TTIR and TTNN dialect and serialize it to flatbuffer
- [ ] Prepare runtime arguments from flatbuffer to structure required in GenericOpDeviceOperation::operation_attributes_t

At the moment it seems that all 3 task are just a matter of implementation, so we shouldn't have problems implementing it and running everything

These 3 tasks should complete running TTNN generic op from TTIR dialect. As @kmitrovicTT 's work is advancing as well, as described in the linked comment, we should be able to run it completely when we complete these tasks

**Comment by pjanevskiTT** [comment]
We have completed 3 tasks from above so we can run everything from TTNN dialect all the way to TTNN. In order to run multiple tests with a lot of different runtime arguments it would be good to have python API for creating runtime arguments and generic op in general. 

Support for runtime arguments is implemented in this [commit](https://github.com/tenstorrent/tt-mlir/commit/938b70599104aa1f80bcb196b1a0564cca42b518). @kmitrovicTT let me know if you would like to change anything in the design of the runtime arguments that would make creating python API easier

**Comment by skhatriTT** [comment]
@nsmithtt do you happen to know our status on this one?

**Comment by nsmithtt** [comment]
I think this is largely done with:
- https://github.com/tenstorrent/tt-metal/pull/20072
